### ISSUE TITLE
on_press condition not working

### ISSUE THREAD

**Issue by maskedpirate** [BinaryTechLabs/Smart-Doorbell#1]
Thanks for the example esphome yaml to make this work. I've wired up a nearly identical wemos d1 mini, with the only difference being my relay is triggered by pin D1 instead of D7. Bringing D0 to high (button press) causes the relay to activate ✔️. Also setting the state of the switch.doorbell_chime_active to true results in appropriate logs on the wemos d1
```
[18:38:35][D][switch:017]: 'Doorbell Chime Active' Turning OFF.
[18:38:35][D][switch:037]: 'Doorbell Chime Active': Sending state OFF
[18:38:35][D][switch:013]: 'Doorbell Chime Active' Turning ON.
[18:38:35][D][switch:037]: 'Doorbell Chime Active': Sending state ON
```
**However - the relay still triggers regardless of the state of switch.doorbell_chime_active.**

My assumption is that the following lines would cause the relay to only trigger when the condition of is_on is true
```
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            - switch.is_on: doorbell_chime_active
          then:
            - switch.turn_on: bs_doorbell_relay
    on_release:
      # On release, turn of the chime.
      - switch.turn_off: bs_doorbell_relay
```
Any help appreciated.
